### ISSUE TITLE
Version & Copyright@AssemblyInfo.cs

### ISSUE THREAD

**Issue by Birgos** [ghusse/MagicExpression#3]
I would like to propose that you change the copyright and version information in the `AssemblyInfo.cs`

**Comment by Timothep** [comment]
Updated as per commit [466b2aa855b6184d546aa8c277e02d22dc5a765c](https://github.com/ghusse/MagicExpression/commit/466b2aa855b6184d546aa8c277e02d22dc5a765c). Thanks for the info!
